# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fe23ht
# "service" is the name of this project. This will also be added to your AWS resource names.
service: Backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"

functions:
  getMenu:
    handler: functions/getMenu/index.handler
    events:
      - httpApi:
          path: /menu
          method: GET

  getOrders:
    handler: functions/getOrders/index.handler
    events:
      - httpApi:
          path: /orders
          method: GET

  getStock:
    handler: functions/getStock/index.handler
    events:
      - httpApi:
          path: /stock
          method: GET

  getUsers:
    handler: functions/getUsers/index.handler
    events:
      - httpApi:
          path: /users
          method: GET

  postOrder:
    handler: functions/postOrder/index.handler
    events:
      - httpApi:
          path: /orders/submit
          method: POST
          cors: true


    # Ny funktion för login
  login:
    handler: login/login.handler
    events:
      - http:
          path: login
          method: post

  # Ny funktion för editMenu
  editMenu:
    handler: functions/getMenu/editMenu.handler
    events:
      - http:
          path: menu/edit
          method: post

  updateOrderStatus:
    handler: functions/updateOrderStatus/index.handler
    events:
      - httpApi:
          path: /orders/update
          method: POST
          cors: true

resources:
  Resources:
    taoMenu:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: taoMenu
        AttributeDefinitions:
          - AttributeName: menuID
            AttributeType: S
        KeySchema:
          - AttributeName: menuID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    taoOrders:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: taoOrders
        AttributeDefinitions:
          - AttributeName: orderID
            AttributeType: S
        KeySchema:
          - AttributeName: orderID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    taoStockpile:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: taoStockpile
        AttributeDefinitions:
          - AttributeName: ingredient
            AttributeType: S
        KeySchema:
          - AttributeName: ingredient
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    taoUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: taoUsers
        AttributeDefinitions:
          - AttributeName: userID
            AttributeType: S
        KeySchema:
          - AttributeName: userID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
